### ISSUE TITLE
[Bug Report] Reset definition retains `return_info`

### ISSUE THREAD

**Issue by arjun-kg** [Farama-Foundation/PettingZoo#824]
**Describe the bug**
I am using a code that uses `utils/conversions` and I get a `TypeError: reset() got an unexpected keyword argument 'return_info'` error. I think from gymnasium 0.26 onwards this argument was supposed to be removed? 

The problem seems to be this: 
 https://github.com/Farama-Foundation/PettingZoo/blob/b8d9c4bdd399601c55a5a3f241b833433bb9e2d3/pettingzoo/utils/conversions.py#L125

I can add PR to fix this if I'm not missing anything here. 

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo (**required**)

**Comment by WillDudley** [comment]
Thank you for spotting this. Would you be able to add that PR, along with a depreciation checker (akin to https://github.com/Farama-Foundation/Gymnasium/blob/5674a52d4c4d7cca9f169db561622b8d3e49bd65/gymnasium/utils/env_checker.py )?

**Comment by Pyrolistical** [comment]
ray rllib has a pr to upgrade to gymnasium 0.28 https://github.com/ray-project/ray/pull/34696

**Comment by elliottower** [comment]
> ray rllib has a pr to upgrade to gymnasium 0.28 [ray-project/ray#34696](https://github.com/ray-project/ray/pull/34696)
We're working on releasing PettingZoo 1.23.0 which will allow that ray PR to work
