### ISSUE TITLE
[Bug Report] ImportError: cannot import name 'simple_spread_v3' from 'pettingzoo.mpe'

### ISSUE THREAD

**Issue by lhw0719** [Farama-Foundation/PettingZoo#1240]
### Describe the bug

Hello,

I am new to MARL and want to createcreate custom parallel env in PettingZoo and wanted to play with it. I am getting the following import error when attempting to get the environments.

from pettingzoo.mpe import simple_spread_v3

`
ImportError: cannot import name 'simple_spread_v3' from 'pettingzoo.mpe'
`

My python version is 3.8.20, petting zoo version is 1.18.1

### Code example

```shell
from pettingzoo.mpe import simple_spread_v3
```

### System info

PettingZoo==1.18.1, python=3.8.20 was installed through pip on Linux

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo

**Comment by lhw0719** [comment]
I find it works well with pettingzoo 1.23.1 and python 3.9.20, which is a versioning issues
